name: Deploy to Hostinger via SSH

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to Hostinger
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."  
          target: "/home/u574044099/public_html/automo-bill"  
          strip_components: 1  

      - name: Set Correct Permissions
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/u574044099/public_html/automo-bill
            chmod -R 775 storage bootstrap/cache
            chmod 644 index.php .htaccess
            find . -type f -exec chmod 644 {} \;
            echo "Deployment Completed"

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: GitHub Deployment Notification
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/approve
